// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameShelf.Migrations
{
    [DbContext(typeof(GameshelfContext))]
    [Migration("20250710105048_AddingData")]
    partial class AddingData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("GameShelf.Entities.GameEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<double>("Rating")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Vast open world action RPG with challenging combat.",
                            Genre = "RPG",
                            Name = "Elden Ring",
                            Price = 59.99m,
                            Rating = 4.9000000000000004
                        },
                        new
                        {
                            Id = 2,
                            Description = "Futuristic open-world RPG in Night City.",
                            Genre = "RPG",
                            Name = "Cyberpunk 2077",
                            Price = 49.99m,
                            Rating = 4.2000000000000002
                        },
                        new
                        {
                            Id = 3,
                            Description = "Epic fantasy RPG with rich storytelling.",
                            Genre = "RPG",
                            Name = "The Witcher 3",
                            Price = 29.99m,
                            Rating = 4.9000000000000004
                        },
                        new
                        {
                            Id = 4,
                            Description = "Action adventure in Norse mythology.",
                            Genre = "Action",
                            Name = "God of War Ragnarok",
                            Price = 69.99m,
                            Rating = 4.7999999999999998
                        },
                        new
                        {
                            Id = 5,
                            Description = "Open-world adventure with robotic creatures.",
                            Genre = "Action",
                            Name = "Horizon Forbidden West",
                            Price = 59.99m,
                            Rating = 4.5999999999999996
                        },
                        new
                        {
                            Id = 6,
                            Description = "Viking saga with exploration and combat.",
                            Genre = "Action",
                            Name = "Assassin’s Creed Valhalla",
                            Price = 39.99m,
                            Rating = 4.2999999999999998
                        },
                        new
                        {
                            Id = 7,
                            Description = "Horror survival in a mysterious European village.",
                            Genre = "Horror",
                            Name = "Resident Evil Village",
                            Price = 34.99m,
                            Rating = 4.4000000000000004
                        },
                        new
                        {
                            Id = 8,
                            Description = "Sci-fi horror classic rebuilt with modern graphics.",
                            Genre = "Horror",
                            Name = "Dead Space Remake",
                            Price = 59.99m,
                            Rating = 4.7000000000000002
                        },
                        new
                        {
                            Id = 9,
                            Description = "Charming farming and life simulation.",
                            Genre = "Simulation",
                            Name = "Stardew Valley",
                            Price = 14.99m,
                            Rating = 4.9000000000000004
                        },
                        new
                        {
                            Id = 10,
                            Description = "Life simulation with character creation and storytelling.",
                            Genre = "Simulation",
                            Name = "The Sims 4",
                            Price = 29.99m,
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 11,
                            Description = "Build and manage realistic cities.",
                            Genre = "Simulation",
                            Name = "Cities: Skylines II",
                            Price = 49.99m,
                            Rating = 4.2999999999999998
                        },
                        new
                        {
                            Id = 12,
                            Description = "Open-world racing in beautiful landscapes.",
                            Genre = "Racing",
                            Name = "Forza Horizon 5",
                            Price = 59.99m,
                            Rating = 4.7999999999999998
                        },
                        new
                        {
                            Id = 13,
                            Description = "Realistic racing simulator with hundreds of cars.",
                            Genre = "Racing",
                            Name = "Gran Turismo 7",
                            Price = 69.99m,
                            Rating = 4.4000000000000004
                        },
                        new
                        {
                            Id = 14,
                            Description = "Fun arcade racing with beloved Nintendo characters.",
                            Genre = "Racing",
                            Name = "Mario Kart 8 Deluxe",
                            Price = 59.99m,
                            Rating = 4.9000000000000004
                        },
                        new
                        {
                            Id = 15,
                            Description = "Modern military shooter with intense action.",
                            Genre = "Shooter",
                            Name = "Call of Duty: MW III",
                            Price = 69.99m,
                            Rating = 4.2000000000000002
                        },
                        new
                        {
                            Id = 16,
                            Description = "Fast-paced battle royale shooter.",
                            Genre = "Shooter",
                            Name = "Apex Legends",
                            Price = 0.00m,
                            Rating = 4.4000000000000004
                        },
                        new
                        {
                            Id = 17,
                            Description = "Tactical team-based shooter.",
                            Genre = "Shooter",
                            Name = "Valorant",
                            Price = 0.00m,
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 18,
                            Description = "Competitive MOBA with strategic gameplay.",
                            Genre = "MOBA",
                            Name = "League of Legends",
                            Price = 0.00m,
                            Rating = 4.5999999999999996
                        },
                        new
                        {
                            Id = 19,
                            Description = "Classic multiplayer online battle arena.",
                            Genre = "MOBA",
                            Name = "Dota 2",
                            Price = 0.00m,
                            Rating = 4.4000000000000004
                        },
                        new
                        {
                            Id = 20,
                            Description = "Sandbox building and survival adventure.",
                            Genre = "Sandbox",
                            Name = "Minecraft",
                            Price = 26.95m,
                            Rating = 4.9000000000000004
                        },
                        new
                        {
                            Id = 21,
                            Description = "2D sandbox exploration and crafting.",
                            Genre = "Sandbox",
                            Name = "Terraria",
                            Price = 9.99m,
                            Rating = 4.7000000000000002
                        },
                        new
                        {
                            Id = 22,
                            Description = "Deep RPG based on D&D rules.",
                            Genre = "RPG",
                            Name = "Baldur’s Gate 3",
                            Price = 59.99m,
                            Rating = 4.9000000000000004
                        },
                        new
                        {
                            Id = 23,
                            Description = "Narrative-driven RPG with philosophical storytelling.",
                            Genre = "RPG",
                            Name = "Disco Elysium",
                            Price = 39.99m,
                            Rating = 4.7999999999999998
                        },
                        new
                        {
                            Id = 24,
                            Description = "Relaxing life sim with charming villagers.",
                            Genre = "Simulation",
                            Name = "Animal Crossing: NH",
                            Price = 59.99m,
                            Rating = 4.7999999999999998
                        },
                        new
                        {
                            Id = 25,
                            Description = "3D platformer with inventive level design.",
                            Genre = "Platformer",
                            Name = "Super Mario Odyssey",
                            Price = 59.99m,
                            Rating = 4.9000000000000004
                        },
                        new
                        {
                            Id = 26,
                            Description = "Atmospheric 2D metroidvania with challenging combat.",
                            Genre = "Platformer",
                            Name = "Hollow Knight",
                            Price = 14.99m,
                            Rating = 4.7999999999999998
                        },
                        new
                        {
                            Id = 27,
                            Description = "Precision platformer with emotional narrative.",
                            Genre = "Platformer",
                            Name = "Celeste",
                            Price = 19.99m,
                            Rating = 4.7000000000000002
                        },
                        new
                        {
                            Id = 28,
                            Description = "Turn-based strategy spanning human history.",
                            Genre = "Strategy",
                            Name = "Civilization VI",
                            Price = 29.99m,
                            Rating = 4.5999999999999996
                        },
                        new
                        {
                            Id = 29,
                            Description = "Epic strategy battles in the Warhammer universe.",
                            Genre = "Strategy",
                            Name = "Total War: Warhammer III",
                            Price = 59.99m,
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 30,
                            Description = "Social deduction party game.",
                            Genre = "Party Game",
                            Name = "Among Us",
                            Price = 4.99m,
                            Rating = 4.2999999999999998
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
